### ISSUE TITLE
CLI: Wallet panics when calling the `faucet` command

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/iota-sdk#2117]
## Description

CLI wallet panics if it isn't connected to a faucet when calling running the `faucet` command.

```sh
Wallet "vps": faucet
panicked at cli/src/wallet_cli/mod.rs:849:20:
a handler must always be installed if the `auto-install` feature is disabled
2024-03-04 08:17:58 (UTC) wallet                                     ERROR panicked at cli/src/wallet_cli/mod.rs:849:20:
a handler must always be installed if the `auto-install` feature is disabled
```

**Comment by Alex6323** [comment]
Did all I can to reproduce it, but probably ran on an old commit that didn't contain the fix 🤷 I will close it for now.
